### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by zachlatta** [leg100/docker-ebs-attach#1]
It'd be nice if you could add a license to this repo. May I suggest MIT? :-)

**Comment by christianromney** [comment]
How do you manage the mount point?

**Comment by zachlatta** [comment]
@christianromney: huh?

**Comment by leg100** [comment]
@zachlatta Very belatedly done, thanks for the heads up: https://github.com/leg100/docker-ebs-attach/commit/1666eca07cf40d5d21c0ae520ddf89b4d8f3e03d

**Comment by zachlatta** [comment]
Thank you for adding!

On Fri, Aug 7, 2015 at 3:45 AM, leg100 notifications@github.com wrote:

> @zachlatta https://github.com/zachlatta Very belatedly done, thanks for
> the heads up: 1666eca
> https://github.com/leg100/docker-ebs-attach/commit/1666eca07cf40d5d21c0ae520ddf89b4d8f3e03d
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/leg100/docker-ebs-attach/issues/1#issuecomment-128670468
> .

## 

## 

Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by leg100** [comment]
@christianromney When I was using this container (a while back now!) I had it started from a systemd unit, say `data-ebs-attach.service`, and that would trigger another systemd unit, `data.mount`, to mount it onto `/data`. If you'd like more information on how I did that, let me know and I'll go into more detail.
